name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    if: github.repository == 'zphyrx/eslint-config'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set pnpm vX
        uses: pnpm/action-setup@v4
        # The version of `pnpm` will be automatically determined from the `packageManager` field in `package.json`
        # No version is explicitly specified to allow the workflow to use the version defined in the project.

      - name: Set Node v22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.20.0
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Check types
        run: pnpm check-types

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Create Release Pull Request or Publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "chore(release): version packages"
          title: "chore(release): version packages"
          version: pnpm run version
          publish: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
